title: <a href="https://github.com/Spikes-2212-Programming-Guild/SpikesLib2" target="_blank" rel="noopener noreferrer">
  <span style="color:rgb(0, 21, 171); font-size:110%; font-weight:bold">SpikesLib</span></a>
description: a Spikes#2212 library
